spring:
          application:
            name: member-service
          cloud:
            nacos:
              discovery:
                server-addr: 192.168.252.162:8848

          server:
            port: 8012

