spring:
  application:
    name: weixin-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.252.162:8848
    sentinel:
      transport:
        dashboard: 192.168.252.162:8070
server:
  port: 8011
feign:
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"


